### ISSUE TITLE
Feature comparison with bond

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#10]
I'd like to make a feature comparison of [bond](https://github.com/fwbrasil/bond) and refined. Maybe @fwbrasil is interested in this too?

**Comment by fwbrasil** [comment]
Sounds good. Let me know if you'd like a review when it's ready.

**Comment by fthomas** [comment]
@fwbrasil I finally came around to write something up: https://github.com/fthomas/refined/blob/master/docs/feature_comparison_bond.md
Please let me know if I missed any feature or if you think the comparison is unfair.
