### ISSUE TITLE
refined-cats is not published for Scala 3.x

### ISSUE THREAD

**Issue by LukaJCB** [fthomas/refined#1038]
first noticed here: https://github.com/tpolecat/skunk/pull/581

Is there something missing or is this just an oversight?

**Comment by fthomas** [comment]
I just tried to enable it in #1040 but the tests in the cats module do not compile with Scala 3.

**Comment by fthomas** [comment]
Ok, I fixed the tests and triggered publishing 0.9.28. refined-cats 0.9.28 for Scala 3 should be available soon.

**Comment by LukaJCB** [comment]
Sweet, thank you so much @fthomas!
