### ISSUE TITLE
Support aliasing RefineM

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#107]
The `RefineM` macro can currently be invoked via the `refineM` functions (e.g. `refineMV[Positive](1)`) or via an implicit conversion which needs to be imported with `import auto._` (it then can be invoked with `1: (Int Refined Positive)`). It would be nice if users of refined could write their own aliases for `RefineM` with fixed types and without importing an implicit conversion. See https://github.com/quasar-analytics/quasar/pull/1025 for more context.

We can support this with a variation of the `RefineMPartiallyApplied` class:
```scala
final class RefineMFullyApplied[F[_, _], T, P] {
  def apply(t: T)(implicit v: Validate[T, P], rt: RefType[F]): F[T, P] = macro RefineM.macroImpl[F, T, P]
}

val Natural = new RefineMFullyApplied[Refined, Long, NonNegative]
```

```scala
scala> Natural(1L)
res3: eu.timepit.refined.api.Refined[Long,eu.timepit.refined.numeric.NonNegative] = Refined(1)

scala> Natural(-1)
<console>:47: error: Predicate (-1 < 0) did not fail.
       Natural(-1)
              ^

scala> Natural(1.3)
<console>:47: error: type mismatch;
 found   : Double(1.3)
 required: Long
       Natural(1.3)
               ^
```

/cc @jedesah

**Comment by wemrysi** [comment]
Nice! :+1:
