### ISSUE TITLE
OpenAPI with Refined Strings

### ISSUE THREAD

**Issue by aurrelhebert** [fthomas/refined#1075]
Hi, 
   I am currently trying to build an API with some refined field (which are strings) and I would to extract if possible a "regExp" pattern directly from the refined type? Is-it something that is possible? 
  
  For example, in my code I declare a type as: 

```
type MyCustomRefinedString = String Refined StartsWith["custom"]
```

  And I would like to generate the OpenAPI spec as, what I would be interested in would be to automatically generate the `pattern` field from my refined type.

```
"MyCustomRefinedString" : {
  "title" : "Custom String",
  "pattern" : "^custom.*$",
  "type" : "string",
  "description" : "A custom string",
  "example" : "custom example string"
},
```

What do you think? Let me know if you need more context

**Comment by strokyl** [comment]
I have contributed something similar to tapir, see:
https://github.com/softwaremill/tapir/pull/405/files

**Comment by strokyl** [comment]
I am not a maintainer of this library, but I don't think we should put OpenAPI logics inside it, this does not seem a good place for that.

**Comment by aurrelhebert** [comment]
Agreed as the available method enable us to define our logic as shown in your code. However maybe, a way to get a human description of a predicate/validator could be interesting.
