### ISSUE TITLE
Publish for Scala native?

### ISSUE THREAD

**Issue by adampauls** [fthomas/refined#1090]
I don't see a Scala native binary on Maven since 0.9.12 (before Scala 3). I see there is still native support in build.sbt; is it broken for some reason, or perhaps it's simply not been published? I'm trying to get native support for circe: https://github.com/circe/circe/pull/1929.

**Comment by fthomas** [comment]
Support for Scala Native has been dropped in https://github.com/fthomas/refined/pull/740 because it was abandoned at that time. I'd merge a PR that brings support for it back to refined.
