### ISSUE TITLE
Replace HList useages with Tuple in scala3 implmentations

### ISSUE THREAD

**Issue by dzanot** [fthomas/refined#1173]
I saw this when looking into the boolean predicates: https://github.com/fthomas/refined/blob/master/modules/core/shared/src/main/scala-3.0%2B/eu/timepit/refined/boolean.scala

It would be nice to use `AllOf` but I'm wary about using hlists in a scala3 project. 

More context: https://discord.com/channels/632277896739946517/920140670394589224/1095773487395774534

**Comment by fthomas** [comment]
I agree that this should be done.

**Comment by dzanot** [comment]
Sweet, I can take a stab on the next rainy weekend.
