### ISSUE TITLE
Benchmarks for compile-time and runtime refinement

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#163]
At the Typelevel Summit in Oslo I was asked about the performance of compile-time and runtime refinements. It would be nice if we could reliably answer things like:
- How does using refined's macro affect compilation time?
- How is the performance of `Validate.isValid` compared to a simple value-level predicate?

**Comment by aaronlevin** [comment]
@fthomas what's the preferred way to do benchmarks in scala? The latter benchmarks should be relatively straight forward. I'd be happy to work on a PR.

**Comment by fthomas** [comment]
@aaronlevin That would be awesome! JMH (Java Microbenchmark Harness) via [sbt-jmh](https://github.com/ktoso/sbt-jmh) would be my tool of choice and I'd copy how circe is doing [its benchmarks](https://github.com/travisbrown/circe/blob/master/benchmark/src/main/scala/io/circe/benchmark/Benchmark.scala) (which are in a separate `benchmark` subproject).

**Comment by fthomas** [comment]
I'll do the compile-time benchmarks with this [`compileTime`](https://github.com/milessabin/shapeless/pull/595) macro once refined is updated to a shapeless version that includes that macro.
