### ISSUE TITLE
Is RefType a Prism in disguise?

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#169]
The main operations of `RefType` are `unwrap` and `refine` if we ignore the unsafe operations and the macros. `unwrap` has type `F[T, P] => T` and `refine` has type `T => Either[String, F[T, P]]`. If we set `type S = F[T, P]` and ignore the error message in `Either`, we get this pair of functions:

``` scala
S => T
T => Option[S]
```

This looks similar to a `Prism`. I'd like to study lens libraries and `Prism` in more detail. Maybe we can borrow laws and concepts from the lens world and streamline `RefType`.

**Comment by fthomas** [comment]
So we can create a `Prism` from a refined type like this:
```diff
--- a/core/shared/src/main/scala/eu/timepit/refined/internal/ApplyRefPartiallyApplied.scala
+++ b/core/shared/src/main/scala/eu/timepit/refined/internal/ApplyRefPartiallyApplied.scala
@@ -2,6 +2,7 @@ package eu.timepit.refined
 package internal
 
 import eu.timepit.refined.api.{ RefType, Validate }
+import monocle.Prism
 
 /**
  * Helper class that allows the types `F`, `T`, and `P` to be inferred
@@ -17,4 +18,29 @@ final class ApplyRefPartiallyApplied[FTP] {
     ev: F[T, P] =:= FTP, rt: RefType[F], v: Validate[T, P]
   ): Either[String, FTP] =
     rt.refine[P](t).right.map(ev)
+
+  def prism[F[_, _], T, P](
+    implicit
+    ev1: F[T, P] =:= FTP, ev2: FTP =:= F[T, P], rt: RefType[F], v: Validate[T, P]
+  ): Prism[T, FTP] =
+    Prism((t: T) => rt.refine[P](t).right.toOption.map(ev1))(tp => rt.unwrap(tp))
 }

```

```scala
scala> type PosInt = Int Refined Positive
defined type alias PosInt

scala> val p = RefType.applyRef[PosInt].prism
p: monocle.Prism[Int,PosInt] = monocle.Prism$$anon$7@6960f5b

scala> p.getOption(4)
res0: Option[PosInt] = Some(4)

scala> p.getOption(-4)
res1: Option[PosInt] = None

scala> p.reverseGet(5: PosInt)
res2: Int = 5
```

**Comment by julien-truffaut** [comment]
I think `RefType` is not always a `Prism` because it doesn't require `f: T => Either[String, F[T, P]]` to be injective on success. See https://github.com/julien-truffaut/Monocle/blob/master/core/shared/src/main/scala/monocle/law/PrismLaws.scala#L16-L17

**Comment by fthomas** [comment]
@julien-truffaut Do you have a specific predicate in mind for which this law does not hold? I couldn't come up with a refined derived prism that violates that law.

**Comment by julien-truffaut** [comment]
Sure, in general `String` provides a lot of examples:
```
scala> scala.xml.XML.loadString("<div></div>").toString
res2: String = <div/>

scala> scala.xml.XML.loadString("<div/>").toString
res3: String = <div/>
```

**Comment by fthomas** [comment]
Aha. But refined's `Xml` predicate does not change a `String` to a `scala.xml.Elem`. It merely tags the source `String` without modifying it:
```scala
scala> "<div></div>": String Refined Xml
res0: eu.timepit.refined.api.Refined[String,eu.timepit.refined.string.Xml] = <div></div>

scala> res0.value
res1: String = <div></div>
```

`scala.xml.XML.loadString` is used in the `Validate[String, Xml]` instance only for checking that the source string is valid XML.

**Comment by julien-truffaut** [comment]
You're completely right. Forget what I said, we should be able to create a `Prism` for all refined type
