### ISSUE TITLE
Module for standard type aliases

### ISSUE THREAD

**Issue by benhutchison** [fthomas/refined#185]
There are some very common refined types that it would be nice to give short, standardized names to.

`Int Refined Positive` and `Int Refined NonNegative` being two examples, which I found myself aliasing after using refined for about an hour.

Without standard names, different users will invariably choose different aliases to refer to the same refinement. Eg I chose `NatInt` and `Nat0Int` for the above two respectively, while [Quasar](https://github.com/quasar-analytics/quasar) apparently uses `Positive` and `Natural`.  

Ideally this is done in a seperate modular layer, so people can opt in to the standard names but aren't forced to use them.

Gitter context: https://gitter.im/fthomas/refined?at=577cca9d9d3eadd723767548

**Comment by benhutchison** [comment]
Thanks @fthomas Im introducing these now to a codebase and finding them useful :)

**Comment by fthomas** [comment]
@benhutchison I'm very pleased to hear that! I'm currently working on #369 which hopefully makes working with type aliases easier.
