### ISSUE TITLE
Core depends on scala-compiler

### ISSUE THREAD

**Issue by clhodapp** [fthomas/refined#207]
The stuff in `generic` is cool. Like super-cool. However, a great deal of the time, you don't need the tremendous power that it provides for defining arbitrary tests. When this is the case, it's really a drag that pulling in refined pulls in `scala-compiler.jar`, as `scala-compiler.jar` is _huge_ (like 15mb). I know it's really a hassle to split projects up into modules, but it would really be great if `generic` was in its own module in order to shrink the disk-wise footprint of refined's dependency set.

**Comment by clhodapp** [comment]
Note that it should be possible to work around this by adding an `exclude` for `scala-compiler` in subprojects, but running an application without some of the classes on the classpath that were there while parts of it were typechecked kind of undermines type safety (and creates a set of APIs that you have to "know" you can't call, lest you get a runtime failure).

**Comment by fthomas** [comment]
If the dependency on `scala-compiler` can be easily moved into a separate project, let's do this. On top of my head I don't know what is pulling this dependency in, so I'll have to check that first.

**Comment by fthomas** [comment]
I traced the addition of the `scala-compiler` dependency back to this *very* early commit https://github.com/fthomas/refined/commit/0cae9c03878773849d6d0b3e1772c00fac7799da which introduced the first macro code into the project. It seems that macros only need a dependency on `scala-reflect` - I need to check if this is sufficient.

**Comment by fthomas** [comment]
First experiments suggest that `scala-reflect` is fine for everything except the implementation of the `generic.Eval` predicate.

**Comment by clhodapp** [comment]
I believe that this is true. However, you may want to move all of `generic` over in order to retain source compatibility for dependent projects (modulo requiring them to include an extra module for `generic`). The drawback to that would be that it would bring in `scala-compiler` if people are using e.g. `generic.Subtype`.

**Comment by fthomas** [comment]
I'd rather break source compatibility for projects using `generic.Eval` instead of requiring `scala-compiler` for using `generic.Equal`. I suspect the former is much less used than the latter.

**Comment by fthomas** [comment]
I did some further experiments and removed everything related to `Eval` from core and replaced the dependency on `scala-compiler` with `scala-reflect`. This compiles just fine but if I try to run the tests which invokes refined's macros, I get the following errors:
```
[error] Class scala.tools.nsc.typechecker.Contexts not found - continuing with a stub.
[error] Class scala.tools.nsc.typechecker.Contexts not found - continuing with a stub.
[error] two errors found
[error] (coreJVM/test:compileIncremental) Compilation failed
```

Other projects that has macros (like shapeless, circe, and Monocle) each have a "provided" dependency on the compiler:
```
"org.scala-lang" % "scala-compiler" % scalaVersion.value % "provided"
```
This fixes the errors above and suggests that core at least requires a "provided" dependency on `scala-compiler` while `Eval` requires a normal dependency on `scala-compiler`.

**Comment by clhodapp** [comment]
I think what you actually have with macros is (at worst) a compile-time-only dependency on the compiler and reflect, but sbt doesn't model that particularly well, hence the use of `provided` in those projects.
