### ISSUE TITLE
Build with Scala 2.12.0

### ISSUE THREAD

**Issue by golem131** [fthomas/refined#214]

**Comment by fthomas** [comment]
Started working on this here: https://github.com/fthomas/refined/compare/topic/2.12.0-final

I guess not all dependencies are available for 2.12.0 yet, so the build will probably fail.

**Comment by fthomas** [comment]
Missing dependencies for 2.12.0:

- [ ] WartRemover: https://github.com/puffnfresh/wartremover/issues/278
- [ ] ScalaCheck: https://github.com/rickynils/scalacheck/issues/291
- [ ] shapeless
- [ ] Macro Paradise
- [ ] macro-compat

**Comment by xeno-by** [comment]
https://oss.sonatype.org/content/repositories/releases/org/scalamacros/paradise_2.12.0/

**Comment by fthomas** [comment]
Thanks @xeno-by!

**Comment by xuwei-k** [comment]
https://oss.sonatype.org/content/repositories/releases/org/typelevel/macro-compat_2.12/1.1.1/

**Comment by fthomas** [comment]
refined 0.6.0 is now available for 2.12.0: https://oss.sonatype.org/content/repositories/releases/eu/timepit/refined_2.12/

It was published from this branch: https://github.com/fthomas/refined/tree/topic/0.6.0-2.12.0
