### ISSUE TITLE
seemless integration with unconstrained types

### ISSUE THREAD

**Issue by cvogt** [fthomas/refined#218]
Has it been considered to have an implicit conversion from `Refined[A,_]` to `A`?

Large parts of our programs will still be using unconstrained types and seemless integration (at least one way) may improve usability of this library.

( related to https://github.com/fthomas/refined/issues/217 )

**Comment by fthomas** [comment]
@cvogt There is [`autoUnwrap`](https://github.com/fthomas/refined/blob/f68a5e551e1993cb3001fd2960b84c08d77bebb0/core/shared/src/main/scala/eu/timepit/refined/auto.scala#L35-L44):
```scala
  /**
   * Implicitly unwraps the `T` from a value of type `F[T, P]` using the
   * `[[api.RefType]]` instance of `F`. This allows a `F[T, P]` to be
   * used as it were a subtype of `T`.
   *
   * Note: This conversion is not needed if `F[T, _] <: T` holds (which
   * is the case for `shapeless.tag.@@`, for example).
   */
```
Which can implicitly convert a `Refined[A, _]` to `A`. Is this sufficient?

**Comment by cvogt** [comment]
Ah yeah, that's it, thx :).
