### ISSUE TITLE
replace or alias `.get` with `.value`

### ISSUE THREAD

**Issue by cvogt** [fthomas/refined#220]
The benefit of a type-system is that the compiler catches your mistakes. Since `.get` is unsafe on `Option[...]` the compiler would not catch mistakenly calling `.get` on what one assumes to be a `Refined` type but actually is an `Option[...]`. Both have the method, but Option can crash.

So maybe there is a case to be made for not calling the accessor `.get` but instead e.g. `.value` as evangelized by sbt. Or some other name without historical baggage of being unsafe.

**Comment by dwijnand** [comment]
:+1: I've changed Some so that it's value is accessible via `value` too.

**Comment by fthomas** [comment]
Agreed. I regret calling the safe accessor `.get`. More so since `Some` got `.value`.

**Comment by cvogt** [comment]
nice :)!
