### ISSUE TITLE
Implicit conversion for libraries dependent on refined (seperating `auto` to trait and object)

### ISSUE THREAD

**Issue by soronpo** [fthomas/refined#239]
Problem:
Libraries which depend on refined types currently force the user to call `import eu.timepit.refined.auto._` to allow standard type variables (literals) to be implicitly converted into their refined types.

Example:
```
  import eu.timepit.refined.api.Refined
  import eu.timepit.refined.api.Validate
  case class ZeroOrOne()
  implicit val zeroOrOneValidate: Validate.Plain[Int, ZeroOrOne] =
    Validate.fromPredicate(p => p == 0 || p == 1, p => s"($p is in not binary)", ZeroOrOne())

  def libFunc(x : Int Refined ZeroOrOne) : Int = x.get
```
`libFunc(1)` fails without the import

Solution (as discussed in [gitter](https://gitter.im/fthomas/refined?at=586044c2058ca967378ed2af)):
Split refined's `auto` into trait and object (see [code](https://github.com/fthomas/refined/blob/master/modules/core/shared/src/main/scala/eu/timepit/refined/auto.scala#L12)). I recommend that the trait's name will be more significant than `auto`.

This will allow the user to extend a companion object to the refined type from that trait, thus allowing the implicit conversion. So the example above changes into:
```
  import eu.timepit.refined.api.Refined
  import eu.timepit.refined.api.Validate
  case class ZeroOrOne()
  object ZeroOrOne extends eu.timepit.refined.api.auto //Or other name if chosen
  implicit val zeroOrOneValidate: Validate.Plain[Int, ZeroOrOne] =
    Validate.fromPredicate(p => p == 0 || p == 1, p => s"($p is in not binary)", ZeroOrOne())

  def libFunc(x : Int Refined ZeroOrOne) : Int = x.get
```

**Comment by fthomas** [comment]
Splitting `auto` in a trait and an object is a low-impact change, so we can certainly do this. What I also like to explore is to mix `auto` into the companion of `Refined` so that the conversions `T => Refined[T, P]` and `Refined[T, P] => T` are in the implicit scope of every refined type so that users of the library do not need to mix `auto` into the companion of their predicates.

**Comment by soronpo** [comment]
>  I need to think about the pros and cons of this approach to decide if we want to do this.

Hmm... What are the cons? Is there a use case where the user will be surprised a conversion happened without an import?

**Comment by fthomas** [comment]
Let's collect the pros and cons here.

pros:
1. Convenient, things "just work" with minimal imports.
1. Using custom predicates does not require any `eu.timepit.refined`
  import or mixing `auto` into their companions.

cons:
1. Implicit conversions can be confusing or unwanted. Suppose you
  want to change a whole API from using `Int` to `PosInt`. If there
  is no implicit `PosInt => Int` in scope, the compiler can help with
  detecting places where you passed a `PosInt` but an `Int` is still
  expected.
1. Works only for `Refined` and not other `RefType`s like
  `shapeless.tag.@@` and `scalaz.@@`.

**Comment by soronpo** [comment]
It is possible to create an `AutoRefined` and have both `Refined` and `AutoRefined` available for use. The supplied refined types like `PosInt` will be `Int AutoRefined Positive`. If someone does not want the implicit then they will declare their own `type MyPosInt = Int Refined Positive`.

**Comment by fthomas** [comment]
It would be nice to resolve this without growing the user-facing API.

**Comment by soronpo** [comment]
The best for **me** is if I don't have an imported macro to my library (when my library extends `auto`), because this limits me if my library uses it directly, and then I have to separate parts of my library. 
I don't mind `Refined` to include `auto`. I also don't mind having a separate `RefinedAuto`, but I understand why you wouldn't want to grow the API.

**Comment by fthomas** [comment]
What do you think about only adding `T => T Refined P` to the `Refined` companion? This way we would only have implicit conversions that provide more type safety without imports.

**Comment by soronpo** [comment]
> What do you think about only adding T => T Refined P to the Refined companion? This way we would only have implicit conversions that provide more type safety without imports.

Makes sense

**Comment by soronpo** [comment]
I'll also elaborate why:
My use case is that the user is feeding values to my library and I want these values to be refined. When I give values back to the user, they are not required to be refined. So implicitly converting only refine-able values to `refined` values makes sense. Therefore a user of my library is not required to know how to translate a literal `Int` to `PosInt`, and if I return values they will be unrefined.

**Comment by soronpo** [comment]
Another though I just had on the matter. While making this change, maybe you can add support for #161 using literal string type.
E.g: `type PosInt = Int Refined["Expecting positive number"] Positive`

**Comment by fthomas** [comment]
@soronpo Sorry for neglecting this issue for so long. I'm wondering if you're still interested in the `AutomaticConversions` trait as outlined above or if you've switched from refined to singleton-ops for the things you are doing. I'm aksing because I think that with the latest release automatic conversions will become less important for users because of the introduction of `RefinedTypeOps` and companion objects for standard refined types. For example, with a single import of `eu.timepit.refined.types.numeric.PosInt` we now not only have the type in scope but also functions to create values of that type from literals or runtime values:
```scala
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_151).
Type in expressions for evaluation. Or try :help.

scala> import eu.timepit.refined.types.numeric.PosInt
import eu.timepit.refined.types.numeric.PosInt

scala> PosInt(1)
res1: eu.timepit.refined.types.numeric.PosInt = 1

scala> PosInt.from(-1)
res2: Either[String,eu.timepit.refined.types.numeric.PosInt] = Left(Predicate failed: (-1 > 0).)

scala> PosInt.unsafeFrom(-1)
java.lang.IllegalArgumentException: Predicate failed: (-1 > 0).
```
No more additional imports are needed now and the value creation has become explicit  which I think I favor in most cases.

**Comment by soronpo** [comment]
Thanks @fthomas. Nice update!
You may now close this issue. I'm using singleton-ops which better fits my use-case.
