### ISSUE TITLE
ClassCastException when using refined with shapeless tags

### ISSUE THREAD

**Issue by felher** [fthomas/refined#271]
Hello folks,

I have a weird interaction between type tags from shapeless and refined types, leading to a class cast exception at runtime. I got the problem down to a few lines of code and put them in the following scastie: http://scastie.org/30039 . The list-wrapping seems to be needed to provoke the CCE.

Maybe I'm just doing something wrong with the tagged types or with refined. If so, please close this ticket.

Thanks for providing this awesome library :)

**Comment by fthomas** [comment]
Thanks for the report! Your example looks perfectly fine to me. I guess value classes (what `Refined` is) and shapeless-style tags do not work very well together. https://github.com/milessabin/shapeless/issues/644 seems to be related.

**Comment by fthomas** [comment]
I'm closing this, since I think it is a bug in shapeless and we can't do anything about this in refined.
