### ISSUE TITLE
Missing implicit value when using Modulo

### ISSUE THREAD

**Issue by ajarbol** [fthomas/refined#317]
When trying to incorporate `Divisible[N]` as a refined type I encounter a problem.
For instance compiling the following:
```
import eu.timepit.refined._
import eu.timepit.refined.numeric.Divisible


object Main {
  type TestT = Divisible[W.`10`.T]
  println(refineT[TestT](10))
}
```
will give me:
```
Error:(9, 25) could not find implicit value for parameter v: eu.timepit.refined.api.Validate[Int,demo.Main.TestT]
  println(refineT[TestT](100))
```
However substituting `Divisible` for something like `Positive` will work without problems. Have others encountered this? It seems to be general for `Modulo[N, O]`

**Comment by fthomas** [comment]
Thanks for the report @ajarbol! Looking at the definition of `Divisible`, I can see why that happens:
```scala
type Divisible[N] = Modulo[N, _0]
```
`_0` there is `shapeless.nat._0`. So your `TestT` type expands to ``Modulo[W.`10`.T, _0]``. The first type argument there is an `Int` and the second a `Nat`. But the library only provides `Validate` instances for `Modulo` if both types are either singleton types with a common `Numeric` instance or  `Nat`s:
```scala
  implicit def moduloValidateWit[T, N <: T, O <: T](
      implicit wn: Witness.Aux[N],
      wo: Witness.Aux[O],
      nt: Numeric[T]
  ): Validate.Plain[T, Modulo[N, O]] =
    Validate.fromPredicate(
      t ⇒ nt.toDouble(t) % nt.toDouble(wn.value) == nt.toDouble(wo.value),
      t ⇒ s"($t % ${wn.value} == ${wo.value})",
      Modulo(wn.value, wo.value)
    )

  implicit def moduloValidateNat[N <: Nat, O <: Nat, T](
      implicit tn: ToInt[N],
      to: ToInt[O],
      wn: Witness.Aux[N],
      wo: Witness.Aux[O],
      nt: Numeric[T]
  ): Validate.Plain[T, Modulo[N, O]] = ???
```
I think we can fix your problem by providing a third instance with the following signature:
```scala
  implicit def moduloValidateWitNat[T, N <: T, O <: Nat](
    implicit wn: Witness.Aux[N],
    to: ToInt[O],
    wo: Witness.Aux[O],
    nt: Numeric[T]
  ): Validate.Plain[T, Modulo[N, O]] = ???
```
where `N` is a numeric singleton type and `O` is a `Nat`. In the meantime you can work around this by defining `TestT` as:
```scala
type TestT = Modulo[W.`10`.T, W.`0`.T]
```
