### ISSUE TITLE
Predicates for BigInt and BigDecimal

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#36]

**Comment by fthomas** [comment]
Closing. These could still be useful but let's add them when they are requested.

**Comment by shokohara** [comment]
I want this function.

**Comment by fthomas** [comment]
@shokohara Unfortunately I hadn't described in details what I meant with this issue, but I think the general idea was to have predicates for `String` which are valid arguments for the `scala.math.BigInt(s: String)` and `scala.math.BigDecimal(s: String)` constructors, for example something like this:
```scala
String Refined ThisIsAValidBigInt
```
Are we taking about the same thing here?

**Comment by kusamakura** [comment]
@fthomas That looks useful, but I'm also running into cases where it would be nice to have BigInts/BigDecimals constructed from literals not result in the `compile-time refinement only works with literals` compile-time error.

**Comment by fthomas** [comment]
@kusamakura This is possible and would just need a small change in `RefineMacro`. [This pattern match](https://github.com/fthomas/refined/blob/b83acba91563ab0a29a2d78f4bebfac6ab10d647/modules/core/shared/src/main/scala/eu/timepit/refined/macros/RefineMacro.scala#L21-L24) would need additional cases for trees that look like `BigInt(<literal>)` and `BigDeciaml(<literal>)`. A PR for that would be very much welcomed. :-)

**Comment by kusamakura** [comment]
@fthomas Thanks for pointing me in the right direction. I think I kind of got it: it works for "normal" cases. I'm quite new to macros, so please excuse the bad code.

```scala
val tValue: T = t.tree match {
  case Literal(Constant(value)) =>
    value.asInstanceOf[T]
  case q"scala.`package`.BigInt.apply(${lit: Literal})" =>
    BigInt(lit.value.value.asInstanceOf[Int]).asInstanceOf[T]
  case q"scala.`package`.BigDecimal.apply(${lit: Literal})" =>
    BigDecimal(lit.value.value.asInstanceOf[Double]).asInstanceOf[T]
  case _ =>
    abort(Resources.refineNonCompileTimeConstant)
}
```

Needless to say, for expressions like `val m: BigInt Refined Positive = BigInt(0x7fffffffffffffffL)`, I get a `ClassCastException`. I'm not sure how I can match on possible types of the literal so it can be passed as an argument to BigInt/BigDecimal constructors. Additionally, that line of thought kind of intersects with your idea for `String Refined ThisIsAValidBigInt` as well.

**Comment by fthomas** [comment]
@kusamakura Pattern matching on the literal value should work:
```scala
    val tValue: T = t.tree match {
      case Literal(Constant(value)) => value.asInstanceOf[T]
      case q"scala.`package`.BigInt.apply(${lit: Literal})" =>
        lit.value.value match {
          case i: Int => BigInt(i).asInstanceOf[T]
          case l: Long => BigInt(l).asInstanceOf[T]
          ...
        }
      ...
      case _                        => abort(Resources.refineNonCompileTimeConstant)
    }
```

**Comment by kusamakura** [comment]
@fthomas Hmm, thanks! Will send a PR your way in a bit.

**Comment by fthomas** [comment]
Closing. https://github.com/fthomas/refined/issues/36#issuecomment-207998825 still applies.

As a side note: additional to `ThisIsAValidBigInt` and `ThisIsAValidBigDecimal`, predicates like `ThisIsAValidInt` and `ThisIsAValidDouble` can be useful too. These hold if `String#toInt` or `String#toDouble` do not throw.

**Comment by kusamakura** [comment]
@fthomas Yes, that would be nice indeed. I would love to find an extensible way without polluting LiteralMatchers all the time though. Any thoughts?

**Comment by fthomas** [comment]
@kusamakura I'm thinking of `ThisIsAValidInt` as a predicate for `String`, i.e. `String Refined ThisIsAValidInt` would be the type of `String`s for which `.toInt` does not throw. So `"123"` would be an inhabitant of that type, but `"abc"` would not. I think there is no need to change `LiteralMatchers` for this. But maybe you have something other in mind?

**Comment by kusamakura** [comment]
@fthomas Right, sorry, I misinterpreted that. I'm working on it. :)
