### ISSUE TITLE
Add refined-scalikejdbc

### ISSUE THREAD

**Issue by sh0hei** [fthomas/refined#389]
cf. https://github.com/scalikejdbc/scalikejdbc

**Comment by howyp** [comment]
Sounds a good idea. What support would you want to see? A `TypeBinder` for refined types would be nice but simple.

**Comment by fthomas** [comment]
I just found a refined integration for scalikejdbc by @katainaka0503 here: https://github.com/katainaka0503/scalikejdbc-refined

I'm inclined to add scalikejdbc-refined to the list of [external modules](https://github.com/fthomas/refined#external-modules) and to just close this ticket. :-)

**Comment by cm-yamasaki-michihiro** [comment]
@fthomas This library is not yet released to public maven repository.  So, I want you to wait until It published.

**Comment by fthomas** [comment]
@cm-yamasaki-michihiro There is no rush from my side, I can wait until it is published. :-)

**Comment by fthomas** [comment]
I'm closing this because I currently don't have enough free time to maintain another integration module in this repo.
