### ISSUE TITLE
[types] Kind of additions

### ISSUE THREAD

**Issue by NeQuissimus** [fthomas/refined#444]
Considering the types package is in the core module, how liberal are you with accepting additions to it?

I have started refining all of our internal messages at work. Some types are common to a lot of them, such as "UNIX file" (i.e. `/tmp/file.zip`) and "valid Kafka topic".
Do you want me to just PR in whatever I come up with and we pick case by case?

**Comment by fthomas** [comment]
This is the first time I'm thinking about guidelines for the types package. I'd say types that are "timeless",  applicable in many contexts, and not to specific to some technology and have a common definition are fine. IMO `PosInt`, `NonEmptyString`, `Second`, and `PortNumber` for example all fall into this category. So "Unix file" probably also falls in this category but "valid Kafka topic" probably not.

If it isn't too much trouble for you, picking case by case sounds good to me.

**Comment by fthomas** [comment]
I'm going to close this issue. @NeQuissimus if you think this should be clarified and/or documented in some kind of FAQ or somewhere else, please reopen it.
