### ISSUE TITLE
scalacheck Arbitrary[A Refined NonEmpty]

### ISSUE THREAD

**Issue by fommil** [fthomas/refined#446]
it seems there is no `scalacheck.collection` module, which means no generator for `String Refined NonEmpty`.

**Comment by fommil** [comment]
I'm not sure how you'd generalise this without using a `Foldable1` or `Monoid` typeclass:

```
  implicit val nonEmptyString: Arbitrary[String Refined NonEmpty] =
    Arbitrary {
      Gen
        .alphaNumStr
        .map(refined.refineV[NonEmpty](_))
        .flatMap {
          case Right(i) => Gen.const(i)
          case Left(_) => Gen.fail
        }
    }
```

**Comment by fthomas** [comment]
This has been recently added for `String Refined NonEmpty` in https://github.com/fthomas/refined/pull/415

**Comment by fommil** [comment]
@fthomas nice!

It should be possible to do this (and `Empty`) for anything with a `Monoid`. Although, I agree that special casing `String` is a good thing. Proposed (not checked it compiles, the `Arbitrary` / `Gen` split confuses me and in fact `refined` makes the whole concept redundant)

```scala
  implicit def nonEmpty[A: Arbitrary: Monoid]: Arbitrary[A Refined NonEmpty] =
    for {
      a <- Arbitrary[A].gen
      b <- Arbitrary[A].gen
    } yield a |+| b

  implicit def empty[A: Monoid]: Arbitrary[A Refined Empty] =
    Arbitrary(Monoid[A].empty)
```

and also for anything with a `Foldable1` (i.e. prior evidence that it is non-empty)

```
 implicit def nonEmptyFoldable1[A: Arbitrary: Foldable1]: Arbitrary[A Refined NonEmpty] =
    Arbitrary[A]
```

with the various calls to "trust me, this will always pass"...
