### ISSUE TITLE
refined-cats: Semigroup for numeric types

### ISSUE THREAD

**Issue by kubukoz** [fthomas/refined#527]
AFAICS it should be possible to define a `Semigroup[A Refined Positive]` for any `A : Semigroup`, as well as for `Semigroup[A Refined Negative]` (adding two negative numbers still gives a negative number).

WDYT about adding something like that to the refined-cats module?

**Comment by kubukoz** [comment]
There could also be semigroups for `Greater[A]` for the same `A`. Ideally given `A < B` we should be able to call `|+|` on values `X Refined Greater[A]` and `Y Refined Greater[B]` and get a `Z Refined Greater[A]`, etc.

**Comment by fthomas** [comment]
I don't think it is possible to derive a `Semigroup[A Refined Positive]` from any `Semigroup[A]`. Here is a contrived counterexample:
```scala
implicit val sg = new Semigroup[Int] { 
  def combine(a: Int, b: Int): Int = -1
}
```
`sg.combine` always returns a negative `Int` and I don't see way to derive a `Semigroup[Int Refined Positive]` from `sg` that only produces positives `Int`s in a generic way.

But adding some specific semigroups / monoids for addition of integral types (e.g. `PosInt` with `+` or `NonNegLong` with `(+, 0)`) should be fine.

**Comment by kubukoz** [comment]
I see... then let's add some instances for actual types :) I'll come up with some PR when I have time.

**Comment by dm-tran** [comment]
I tried to implement some Semigroup instances and tested them using [cats-laws](https://typelevel.org/cats/typeclasses/lawtesting.html).

```
def getPosSemigroup[A: Semigroup](implicit v: Validate[A, Positive]): Semigroup[A Refined Positive] =
  Semigroup.instance{ (x, y) =>
    val combined: A = Semigroup[A].combine(x.value, y.value)
    refineV[Positive](combined).right.get
  }

implicit val posByteSemigroup: Semigroup[PosByte] = getPosSemigroup[Byte]
implicit val posShortSemigroup: Semigroup[PosShort] = getPosSemigroup[Short]
implicit val posIntSemigroup: Semigroup[PosInt] = getPosSemigroup[Int]
implicit val posLongSemigroup: Semigroup[PosLong] = getPosSemigroup[Long]
implicit val posFloatSemigroup: Semigroup[PosFloat] = getPosSemigroup[Float]
implicit val posDoubleSemigroup: Semigroup[PosDouble] = getPosSemigroup[Double]
```

Law tests for PosFloat and PosDouble sometimes fail, because floating point addition is not associative (but this is also the case for Float and Double). For instance:
```
[info] - PosDouble.SemigroupLaws.semigroup.associative *** FAILED ***
[info]   GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.
[info]    (Discipline.scala:14)
[info]     Falsified after 36 successful property evaluations.
[info]     Location: (Discipline.scala:14)
[info]     Occurred when passed generated values (
[info]       arg0 = 9.340072777762638E306,
[info]       arg1 = 1.086719613711463E308,
[info]       arg2 = 4.824697924817917E307
[info]     )
[info]     Label of failing property:
[info]       Expected: 1.662590133970881E308
[info]   Received: 1.6625901339708811E308
```

And it turns out that the sum of two PosByte/PosShort/PosInt/PosLong isn't always positive:
```
scala> Byte.MaxValue |+| 1
res6: Byte = -128
```

A workaround is to return the MaxValue if the result is negative, but this could be misleading for users. WDYT ?

```
def getPosNonFloatingPointSemigroup[A: Semigroup: Max](implicit v: Validate[A, Positive]): Semigroup[A Refined Positive] =
  Semigroup.instance{ (x, y) =>
    val combined: A = Semigroup[A].combine(x.value, y.value)
    refineV[Positive](combined).getOrElse {
      refineV[Positive](Max[A].max).right.get
    }
  }

implicit val posByteSemigroup: Semigroup[PosByte] = getPosNonFloatingPointSemigroup[Byte]
implicit val posShortSemigroup: Semigroup[PosShort] = getPosNonFloatingPointSemigroup[Short]
implicit val posIntSemigroup: Semigroup[PosInt] = getPosNonFloatingPointSemigroup[Int]
implicit val posLongSemigroup: Semigroup[PosLong] = getPosNonFloatingPointSemigroup[Long]
```

With those instances, we would e.g. have:
```
scala> PosByte.MaxValue |+| PosByte.unsafeFrom(1)
res21: eu.timepit.refined.types.numeric.PosByte = 127
```

**Comment by fthomas** [comment]
I would argue that if an integral type overflows on addition, a refined integral type should too for consistency. So ` PosByte.MaxValue |+| PosByte.unsafeFrom(1)` would be `1: PosByte`. I experimented with addition of `NonNegInt` [here](https://github.com/fthomas/refined/issues/217#issuecomment-357460213) but never came around adding this to the library.

**Comment by dm-tran** [comment]
That makes sense and it's much better than returning the MaxValue. I will try to work on it and submit a PR.
