### ISSUE TITLE
RFE: implicit conversion from Refined values back to raw values

### ISSUE THREAD

**Issue by erikerlandson** [fthomas/refined#55]
Support implicit conversion from a Refined value to its raw value, as in:
 `implicit def toRaw[T, P](r: Refined[T, P]):T = r.get`

Mostly just a question of where best to define it, so it is easy to include.
REPL Example:

``` scala
scala> val x: Int Refined NonNegative = 3
x: eu.timepit.refined.Refined[Int,eu.timepit.refined.numeric.NonNegative] = Refined(3)

scala> x + 5
<console>:45: error: value + is not a member of eu.timepit.refined.Refined[Int,eu.timepit.refined.numeric.NonNegative]

scala> implicit def toRaw[T, P](r: Refined[T, P]):T = r.get

scala> x + 5
res2: Int = 8
```

**Comment by fthomas** [comment]
:+1:

I would put it into https://github.com/fthomas/refined/blob/master/shared/src/main/scala/eu/timepit/refined/implicits.scala, call it `autoUnwrap` and make it available for all `F[_, _]` with a `RefType` instance (similar to `autoInfer`).
