### ISSUE TITLE
Add new collection predicates: Contains, Index, and Unique

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#6]
`Contains` is just a type alias (`Contains[A] = Exists[Equal[A]]`), `Index[N, P]` checks if the value at index `N` satisfies the predicate `P`, and `Unique` checks if all elements in a collection are unique.

**Comment by jgpacker** [comment]
For ordered collections, we could also have a `Sorted[A]` predicate.
Thourhg I'm not sure how the user could choose between ascendent and descendent order.

**Comment by fthomas** [comment]
Good idea, @jgpacker ! We could have `SortedAsc` and `SortedDesc` or provide an extra type for the sort order: `trait SortOrder; trait Ascending extends SortOrder; trait Descending extends SortOrder`. Another possibility is to have something like `SortedWith[P]` where `P` is some kind of binary predicate (which we don't have yet). For example: `SortedWith[GreaterEqual2]` where `GreaterEqual2` gives you a `BinaryPredicate` instance with `isValid(t1: T, t2: T): Boolean = t1 >= t2`.

**Comment by fthomas** [comment]
Another collection predicate: `IndexWhere[PA, PI]`. It could be used like this `IndexWhere[Digit, LessEqual[_2]]` which validates any collection of `Char` where one of the first three chars is a digit.

**Comment by fthomas** [comment]
And `Head[P]`, `Last[P]`, `Tail[P]`, `Init[P]`, ...

**Comment by fthomas** [comment]
`SortedWith` as outlined in https://github.com/fthomas/refined/issues/6#issuecomment-105045917 is a misnomer. It should better be called `Pairwise[P]` since it checks if consecutive pairs of elements in a sequence satisfy the binary predicate `P`.

**Comment by sh0hei** [comment]
Hi, @fthomas :)

I want to Implement `Unique` Predicate.
I want you to tell me Signature of `Unique` and Usage of `Unique`.

**Comment by fthomas** [comment]
@sh0hei The idea of `Unique` is that it checks that a collection has no duplicated elements. It has no parameters, so would be defined as empty case class: `case class Unique()`.

Usage would look something like this:
```scala
type UniqueList[A] = List[A] Refined Unique 

scala> RefType.applyRef[UniqueList[Int]](List(1, 2, 3))
res0: Either[String, UniqueList[Int]]= Right(Refined(List(1, 2, 3)))

scala>RefType.applyRef[UniqueList[Int]](List(1, 2, 2))
res1: Either[String, UniqueList[Int]]= Left("Predicate failed: List(1, 2, 2) contains duplicated elements: 2")
```

**Comment by sh0hei** [comment]
okay :)
I try it !

**Comment by fthomas** [comment]
Awesome! :-)

**Comment by sh0hei** [comment]
@fthomas Excuse me, I'd like also to know about Usage `Tail`, `Init`. I'll try to implement it.

**Comment by fthomas** [comment]
@sh0hei `Tail` and `Init` would be similar to the already existing `Head` and `Last` predicates (see [collection.scala](https://github.com/fthomas/refined/blob/master/core/shared/src/main/scala/eu/timepit/refined/collection.scala)). They check if all but the first/last element of a sequence satisfy a given predicate.

**Comment by fthomas** [comment]
Closing since most of the predicates in this ticket are now implemented.

**Comment by fthomas** [comment]
@kubukoz It hasn't been implemented yet. :) But I'm open to adding `Sorted` or `Sorted{Asc, Desc}` or something similar to the librarary.
