### ISSUE TITLE
autoUnwrap does not kick in when refined type is used in expression

### ISSUE THREAD

**Issue by Methrat0n** [fthomas/refined#608]
The `eu.timepit.refined.auto.autoUnwrap` implicit conversion does not work when used in expressions.

Example :
```scala
import eu.timepit.refined.api.Refined
import eu.timepit.refined.numeric.Positive
import eu.timepit.refined.auto._

type PositiveInt = Int Refined Positive

val i1: PositiveInt = 5
val i2: PositiveInt = 5

val i3: Int = i1 + i2
```

The last line complains about the + function not being defined for PositiveInt. The autoUnwrap function  work when used directly : 
```scala
val i3: Int = autoUnwrap(i1) + autoUnwrap(i2)
```

In comparison a simpler definition works fine, for example this one :
```scala
@inline implicit def refinedType2Base[Predicate, Base](refinedType: Base Refined Predicate): Base = refinedType.value
```

It would be great if the autoUnwrap def would be called here, as calling `.value`on each Refined type is cumbersome.

**Comment by fthomas** [comment]
Thanks for the report, @Methrat0n! It seems that adding a type parameter for the predicate also does the trick:
```diff
-  implicit def autoUnwrap[F[_, _], T](tp: F[T, _])(implicit rt: RefType[F]): T =
+  implicit def autoUnwrap[F[_, _], T, P](tp: F[T, P])(implicit rt: RefType[F]): T =
```
And then:
```scala
scala> PosInt(1) + PosInt(2)
res0: Int = 3
```
