### ISSUE TITLE
Can we refine Int to restrict to valid minutes, hours?

### ISSUE THREAD

**Issue by julien-truffaut** [fthomas/refined#63]
Similar to `NonNegative Int` but for Int limited to `[0 .. 60]` or `[0 .. 24]`

I would like to use this new types to define lawful `Lens` on `Date` e.g.

```scala
val minute: Lens[Date, Minute] = ???

minute.set(30)(d)   // ok
minutes.set(79)(d) // compile error
```

**Comment by fthomas** [comment]
We can refine `Int` with the `Interval` predicate to create types for hours, minutes, or seconds:
```scala
scala> type Minute = Int Refined Interval[W.`0`.T, W.`59`.T]
defined type alias Minute

scala> 20: Minute
res0: Minute = Refined(20)

scala> 70: Minute
<console>:48: error: Right predicate of (!(70 < 0) && !(70 > 59)) failed: Predicate (70 > 59) did not fail.
       70: Minute
       ^
```

The interesting question is now how to construct a lawful `Lens[Date, Minute]`. I'll have a look at Monocle to see how far I can get.

**Comment by julien-truffaut** [comment]
I think it should not be too difficult:

```scala
import org.joda.time.DateTime
import monocle.Lens

type Minute = Int Refined Interval[W.`0`.T, W.`59`.T]

val minute: Lens[DateTime, Minute] = Lens(_.getMinuteOfHour : Minute)(m => d => d.withMinuteOfHour(m))
```

**Comment by fthomas** [comment]
The ascription `: Minute` will invoke a macro that tries to check if the value of `getMinuteOfHour` is a valid `Minute`. Since that value is not available at compile-time, the macro will fail. It can only check literal values. But because we know that `getMinuteOfHour` will only return `Int`s that are valid `Minute`s, we can just wrap it in the `Refined` value class without validation.

Here is my first attempt of defining a `Lens` with `Minute`:
```scala
val minute = Lens[LocalDateTime, Minute](
  d => Refined.unsafeApply(d.getMinute))(
  m => d => d.withMinute(m.get))
```

The complete example is here: https://github.com/fthomas/refined/compare/topic/monocle

**Comment by julien-truffaut** [comment]
right, make sense to use `unsafeApply`.

I am going to create a module in monocle to play with that :)

**Comment by julien-truffaut** [comment]
@fthomas any idea why I am getting the following error:
```
object auto is not a member of package eu.timepit.refined
[error] import eu.timepit.refined.auto._
```

I am using `"eu.timepit"      %% "refined"     % "0.2.3"`

**Comment by fthomas** [comment]
`auto` is the new name of the recently deprecated `implicits` object and is only available in `master`. Sorry, I should have mentioned that. In the current stable version just do
```scala
import eu.timepit.refined.implicits._
```

**Comment by fthomas** [comment]
@julien-truffaut I think https://github.com/julien-truffaut/Monocle/compare/date nicely demonstrates that lenses and refined types can be combined in a useful way. Is there anything else from the refined side we need to explore or improve before we can declare victory? :-) If not I'd like to close this issue.

**Comment by julien-truffaut** [comment]
No it is working very well and it was very easy to setup. Thanks.
