### ISSUE TITLE
Email Regex getting ` Malformed literal` error

### ISSUE THREAD

**Issue by UkonnRa** [fthomas/refined#663]
Say a Email MatchesRegex: `type EmailType = MatchesRegex[W.`"^[\\w.+-_]+@[^.][\\w.-]*\\.[\\w-]{2,63}$"`.T]`.

Get an error when compiling:

```
Error: Malformed literal "^[\w.+-_]+@[^.][\w.-]*\.[\w-]{2,63}$"
  type EmailType = MatchesRegex[W.`"^[\\w.+-_]+@[^.][\\w.-]*\\.[\\w-]{2,63}$"`.T]
```

Any idea?

**Comment by fthomas** [comment]
Using triple quotes for the regular expression might help: ``MatchesRegex[W.`"""..."""`.T]``
