### ISSUE TITLE
Update Maven central badge to 0.3.0

### ISSUE THREAD

**Issue by julien-truffaut** [fthomas/refined#70]
Btw, is there a release note?

**Comment by julien-truffaut** [comment]
I am stupid, it will probably be updated automatically once it has been sync

**Comment by fthomas** [comment]
It is annoying that syncing always takes a while... I always find it hard to announce hours after doing the release :)

Release notes are here https://github.com/fthomas/refined/blob/master/notes/0.3.0.markdown
