### ISSUE TITLE
Remove xml from core

### ISSUE THREAD

**Issue by jhnsmth** [fthomas/refined#711]
I'd like to propose removement of xml dependency from core. I believe it's there only for historical reason, as previously xml was a part of scala standard library.

Together with #647 this allows to have a single shapeless dependency in core. 

If this change is welcome, I'm happy to make a PR as well as other necessary steps.

**Comment by fthomas** [comment]
This already happened in #610 which was merged into the `series/0.10` branch because it is a binary and source incompatible change. I guess it is time now to merge this branch in master and to bump the version to 0.10.

**Comment by jhnsmth** [comment]
Oh, sorry I did not know that there is a branch for upcoming version. Lets close this issue then.
