### ISSUE TITLE
RefineSyntaxSpec fails on latest Scala 2.13 nightly (progression?)

### ISSUE THREAD

**Issue by SethTisue** [fthomas/refined#718]
this arose in the Scala community build at https://github.com/scala/community-build/pull/1056

it's reproducible outside dbuild with `++2.13.2-bin-23f0ead` followed by `coreJVM / Test / compile`

```
[error] /Users/tisue/refined/modules/core/shared/src/test/scala/eu/timepit/refined/RefineSyntaxSpec.scala:59:13: Type-checking failed in an unexpected way.
[error] Expected error matching: could not find implicit value.*
[error] Actual error: Predicate failed: (-1 > 0).
[error]     illTyped("testRefineMV(refineMV(-1))", "could not find implicit value.*")
[error]             ^
[error] /Users/tisue/refined/modules/core/shared/src/test/scala/eu/timepit/refined/RefineSyntaxSpec.scala:66:13: Type-checking failed in an unexpected way.
[error] Expected error matching: could not find implicit value.*
[error] Actual error: Predicate failed: (-1 > 0).
[error]     illTyped("testRefineMT(refineMT(-1))", "could not find implicit value.*")
[error]             ^
```

offhand it looks like a progression rather than a regression, is that guess right?

**Comment by fthomas** [comment]
Yes, that indeed looks like a progression. It seems to me that the compiler now inferred `Positive` as type parameter for `refineMV` based on the type of `testRefineMV`.

Is there anything I could do so that you don't need to maintain a fork of refined for the community build? I guess one option would be to just not check the error message in this case.

**Comment by SethTisue** [comment]
> Is there anything I could do so that you don't need to maintain a fork of refined for the community build?

Even if you do nothing now, you'll hit this in a month or so when Scala 2.13.2 comes out — either the test will need to become more flexible, or you won't be able to upgrade. So I presume you'll do.... something.... if not now, then later... and then I can unfork in the community build.

Not checking the message, with a comment about why, seems like a reasonable solution to me.

**Comment by fthomas** [comment]
> Not checking the message, with a comment about why, seems like a reasonable solution to me.

Ok, will do that then. Thanks @SethTisue!
