### ISSUE TITLE
Publish for scala.js 1.0

### ISSUE THREAD

**Issue by cquiroz** [fthomas/refined#744]
Refined is required by several libraries downstream and in turn refined is waiting for shapless support for scala.js 1.0

**Comment by fthomas** [comment]
Any help with this would be much appreciated!

**Comment by cquiroz** [comment]
I'm trying to build but we are missing some dependencies

**Comment by xuwei-k** [comment]
I think all dependencies published. shapeless published few hours ago.
https://github.com/milessabin/shapeless/pull/967#issuecomment-593135545
https://repo1.maven.org/maven2/com/chuusai/shapeless_sjs1_2.13/

**Comment by fthomas** [comment]
I'm also okay with just publishing the core module for Scala.js 1.0.0. This should already unblock the most downstream dependencies.

**Comment by cquiroz** [comment]
scalaz needs to be upgraded to suppor scala.js 1.0. I tried but it leads to non trivial code changes. Do you think it could be skipped?

**Comment by fthomas** [comment]
Yes, I'm fine with not publishing the scalaz module for Scala.js 1.0.

**Comment by fthomas** [comment]
refined 0.9.13 is now available for Scala.js 1.0.

Thanks @cquiroz for your help!
