### ISSUE TITLE
Add error accumulating function to RefType

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#75]
Add a function to `RefType` that is similar to `refine` but instead of returning an `Either` it should return a type that can accumulate errors (something like [`cats.Validated`](http://non.github.io/cats//tut/validated.html)). bond has this as can be seen here: https://github.com/fthomas/refined/blob/v0.8.2/modules/docs/feature_comparison_bond.md#what-bond-has-but-refined-not

**Comment by fthomas** [comment]
https://meta.plasm.us/posts/2015/12/17/error-accumulating-decoders-in-circe/ might be interesting here.

**Comment by ysusuk** [comment]
hi @fthomas, i'll be glad to work on this issue) can you give me some hints on where to start?

**Comment by ysusuk** [comment]
hi @fthomas 
did you mean as well to create another `RefinePartiallyApplie` in cats package, that will return ValidatedNel instead of Either?

**Comment by fthomas** [comment]
@ysusuk Yes. :-)

**Comment by ysusuk** [comment]
@fthomas can you pls assign this issue on me)

**Comment by fthomas** [comment]
It seems that I only can assign it to myself.

**Comment by fthomas** [comment]
I'm closing this in favor of #382.
