### ISSUE TITLE
Validate runtime value?

### ISSUE THREAD

**Issue by sergeda** [fthomas/refined#776]
I have this code:

```
def test(value: String): Unit = {
type TrimmedNonEmpty = NonEmptyString Refined Trimmed
val v: Either[String, TrimmedNonEmpty] = refineV(value)
}
```
On last line I've got error "compile-time refinement only works with literals" at compile time.
Why is it so? As I understand refineV should work with runtime values?

**Comment by fthomas** [comment]
`TrimmedNonEmpty` should be defined as `String Refined (NonEmpty And Trimmed)`. `NonEmptyString` is an alias for `String Refined NonEmpty`, so your type alias dealiases to `(String Refined NonEmpty) Refined Trimmed` and the library can't work with such types.

**Comment by sergeda** [comment]
Thanks a lot
