### ISSUE TITLE
The derived instance `Arbitrary[NonEmptyFiniteString[N]]` may generate an empty string

### ISSUE THREAD

**Issue by Hjdskes** [fthomas/refined#792]
Because `NonEmptyFiniteString[N]` is a `String Refined Size[Interval.Closed[_1, N]]` without a dedicated `Arbitrary[NonEmptyFiniteString[N]]` instance, for `Arbitrary[NonEmptyFiniteString[N]]` we end up in `stringSizeArbitrary` from `eu.timepit.refined.scalacheck.string`:

```scala
implicit def stringSizeArbitrary[F[_, _]: RefType, P](
      implicit
      arbChar: Arbitrary[Char],
      arbSize: Arbitrary[Int Refined P]
  ): Arbitrary[F[String, Size[P]]] =
    collection.buildableSizeArbitrary[F, String, Char, P]
```

This function defers to `collection.buildableSizeArbitrary`:

```scala
  // This is private and not implicit because it could produce invalid
  // values for some collections:
  //
  // scala> buildableSizeArbitrary[Refined, Set[Boolean], Boolean, Equal[3]].arbitrary.sample
  // res0: Option[Refined[Set[Boolean], Size[Equal[3]]]] = Some(Set(false, true))
  private[scalacheck] def buildableSizeArbitrary[F[_, _]: RefType, C, T, P](
      implicit
      arbT: Arbitrary[T],
      arbSize: Arbitrary[Int Refined P],
      ev1: Buildable[T, C],
      ev2: C => Traversable[T]
  ): Arbitrary[F[C, Size[P]]] =
    arbitraryRefType(arbSize.arbitrary.flatMap { n =>
      Gen.buildableOfN[C, T](n.value, arbT.arbitrary)
    })
```

The comment on this function already alludes to the problem: `Gen.buildableOfN` returns a container of maximum size `N`, but it may contain fewer elements. In the case of `NonEmptyFiniteString[N]`, this means that an empty string may be returned from this function, breaking the contract of `NonEmptyFiniteString[N]`.

I believe the right way to solve this would be to add a dedicated instance for `Arbitrary[NonEmptyFiniteString[N]]` that adds an extra check on the result of `buildableSizeArbitrary`:

```scala
  implicit def nonEmptyFiniteStringArbitrary[F[_, _]: RefType, N <: Int](
    implicit wn: Witness.Aux[N]
  ): Arbitrary[F[String, Size[Interval.Closed[_1, N]]]] =
    arbitraryRefType[F, String, Size[Interval.Closed[_1, N]]](
      Gen.buildableOfN[String, Char](wn.value, Gen.alphaNumChar).suchThat(_.nonEmpty)
    )
```

Alternatively, we could add a `buildableNonEmptySizeArbitrary` if you prefer to keep things general, although this leads to duplication and arguably `NonEmptyFiniteString` would be the only user of this:

```scala
  private[scalacheck] def buildableNonEmptySizeArbitrary[F[_, _]: RefType, C, T, P](
        implicit
        arbT: Arbitrary[T],
        arbSize: Arbitrary[Int Refined P],
        ev1: Buildable[T, C],
       ev2: C => Traversable[T]
  ): Arbitrary[F[C, Size[P]]] =
    arbitraryRefType(arbSize.arbitrary.flatMap { n =>
      Gen.buildableOfN[C, T](n.value, arbT.arbitrary).suchThat(_.nonEmpty)
    })
```

Let me know if you have any other suggestions. I'll be happy to open a PR with a fix once we agree on what it looks like!

**Comment by fthomas** [comment]
> `Gen.buildableOfN` returns a container of maximum size N, but it may contain fewer elements.

This is bad. `buildableSizeArbitrary` is buggy if it does not create collections that conform to `Size[P]`. I understand that it doesn't work for `Set` and similar data types but it is strange that it can't always generate a `String` of the given size. I guess we need to add a `.suchThat(_.size == n.value)` to `buildableSizeArbitrary`.

**Comment by Hjdskes** [comment]
Note that I am not sure we have actually seen this behaviour -- I just noticed it while I was browsing the implementation of things. I should have mentioned this in the initial issue.

**Comment by Hjdskes** [comment]
> I guess we need to add a `.suchThat(_.size == n.value)` to `buildableSizeArbitrary`.

This depends on the user of `buildableSizeArbitrary`. For `NonEmptyFiniteString[N]` we only need to verify that the string is not empty, i.e., we only need `.suchThat(_.nonEmpty)`. If we'd add `.suchThat(_.size == n.value)` for `NonEmptyFiniteString[N]` we would prevent the generation of strings with length between 1 and n-1 which would preclude a lot of valid values.

**Comment by fthomas** [comment]
The `n` I was talking about comes from `arbSize: Arbitrary[Int Refined P]` parameter of `buildableSizeArbitrary` and is not the same as the upper bound `N` in `NonEmptyFiniteString[N]`:
https://github.com/fthomas/refined/blob/6fb4a4e45b2c103fea11472e9c3153349b89ae73/modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/collection.scala#L34-L35

**Comment by fthomas** [comment]
I'm inclined to close this since I think that `buildableSizeArbitrary` will always generate a `String` of the requested size. I assume the [`comment on Gen.buildableOfN`](https://github.com/typelevel/scalacheck/blob/433b7a2d370f2136515d4d0b7893f6c612aefae8/src/main/scala/org/scalacheck/Gen.scala#L654-L663) that it may generate containers with fewer elements than requested only applies to `Set` and similar types but not to `String`.

WDYT @Hjdskes? Am I missing something?

**Comment by Hjdskes** [comment]
I think you may be right. We also have test case for `NonEmptyFiniteString` in `StringArbitrarySpec` that would (hopefully) fail otherwise.

**Comment by fthomas** [comment]
OK, closing then.
