### ISSUE TITLE
Rfc1918ClassBPrivateSpec incorrect matches

### ISSUE THREAD

**Issue by jbenoit2011** [fthomas/refined#795]
[Rfc1918ClassBPrivateSpec](https://github.com/fthomas/refined/blob/e64f11c6f4bcb322ceac76da4011c7e993838f5b/modules/core/shared/src/main/scala/eu/timepit/refined/types/net.scala#L79) matches IPs out of RFC range.
For example, `172.222.171.197` will match.
This is caused by a missing escaping backslash before the latest dot in the regex.
Actually, the regex is `^172\.(15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31).+`, the latest dot is considered as a wildcard character because not escaped, so any IP with a second digit starting with characters 15 to 31 will match.

Adding a backslash before, solve the issue: `^172\.(15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)\.+`

Here is a scastie to test: https://scastie.scala-lang.org/ktfISeSZQNG9iLt7MvUg0g

May I send a PR?

Thanks.

**Comment by fthomas** [comment]
Thanks for the report, @jbenoit2011! A PR would be very welcome.
