### ISSUE TITLE
Add type aliases for open and half-closed intervals?

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#80]
Currently `Interval[x, y]` represents the closed interval `[x, y]`. Do we want aliases for half-closed and open intervals: `[x, y)` `(x, y]`, `(x, y)`?

**Comment by fthomas** [comment]
Possible names for those aliases are:
 * `IntervalCC` for `[]`
 * `IntervalCO` for `[)`
 * `IntervalOC` for `(]`
 * `IntervalOO` for `()`

Better suggestions are always welcome!

**Comment by fthomas** [comment]
More name proposals:
 * `Interval` for `[]`
 * `RightOpenInterval` for `[)`
 * `LeftOpenInterval` for `(]`
 * `OpenInterval` for `()`

**Comment by rueger** [comment]
You may have a look to Google Guava ranges https://code.google.com/p/guava-libraries/wiki/RangesExplained which have names like closedOpen(C, C) for [a..b)

**Comment by fthomas** [comment]
Interesting, thanks! Those names combined with an additional namespace `object` look really nice:
```scala
object Interval {
  type Closed[L, H] = ...
  type ClosedOpen[L, H] = ...
  type OpenClosed[L, H] = ...
  type Open[L, H] = ...
}

// usage:
val x: Int @@ Interval.Open[L, H] = ...
```
