### ISSUE TITLE
monocle + refined for bit indexing into primitives?

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#85]
@julien-truffaut mentioned on [Gitter](https://gitter.im/julien-truffaut/Monocle/archives/2015/11/04) an idea about using refined for a type class that provides a `def indexLens(i: I): Lens[S, A]` (where `I` is a refined type that is constrained by the bit length of `S`?) for bit indexing into primitive data types. I'd like to play with this idea and want to see how refined can be used here.

**Comment by fthomas** [comment]
I've played a little bit with a `SafeAt` type class here: https://github.com/fthomas/refined/blob/a5be764ee04200cb8e1a01f7724a022f86d0559c/core/jvm/src/main/scala/eu/timepit/refined/SafeAt.scala

I think that comes pretty close to what @julien-truffaut had in mind.

**Comment by julien-truffaut** [comment]
it is exactly what I had in mind! I am even surprise of the syntax, I was expecting some wrapper around the index but that's amazing we can use literals.

Where do you think this code should live? I am happy to create a refined module in monocle but you might prefer other options.

**Comment by fthomas** [comment]
The index is actually wrapped into `Refined` but we don't see it because an `auto._` import brings in an implicit macro that converts the `Int` literals to ``Int Refined ZeroTo[W.`7`.T]`` or fails to compile.

I'd love to if this could live in monocle. I've no problem putting it in refined, but if I do it might be perceived that I'm the only one who thinks this stuff is useful. :smile:

**Comment by fthomas** [comment]
PR in monocle: https://github.com/julien-truffaut/Monocle/pull/291
