### ISSUE TITLE
Add JsonPath predicate

### ISSUE THREAD

**Issue by fthomas** [fthomas/refined#88]
... using https://github.com/jayway/JsonPath to determine if a `String` is a valid JSON path or not. This should be similar to the `XPath` predicate.

**Comment by ysusuk** [comment]
hi @fthomas correct me if i'm wrong, this predicate should only be available on jvm, not js. since from js you cannot use java libs?

**Comment by fthomas** [comment]
Yes, that's right. Of course a Scala library for JsonPath that is available for Scala.js (and maybe Scala Native) would be preferable. Since this predicate requires a new dependency it also should go into a new module. The less dependencies in the core module the better.

**Comment by ysusuk** [comment]
@fthomas this can be closed!? =)

**Comment by fthomas** [comment]
Right! :-)

Closed by #305
