### ISSUE TITLE
Reduce amount of imports needed

### ISSUE THREAD

**Issue by Fristi** [fthomas/refined#884]
A while back I gave presentation about refined and I stumbled on the fact that you need a few imports to get going:

https://fristi.github.io/refined-deck/#5

For better ergonomics it would be great if we can reduce it

**Comment by fthomas** [comment]
```
import eu.timepit.refined.generic._
import eu.timepit.refined.char._
import eu.timepit.refined.boolean._
import eu.timepit.refined.collection._
import eu.timepit.refined.numeric._
import eu.timepit.refined.string._
```
can be replaced with `import eu.timepit.refined.predicates.all._` and
```
import eu.timepit.refined.types.numeric._
import eu.timepit.refined.types.string._
```
can be replaced by `import eu.timepit.refined.types.all._`

**Comment by Fristi** [comment]
Thanks, quite an improvement :)
