### ISSUE TITLE
3.0.0-M3 release?

### ISSUE THREAD

**Issue by tpolecat** [fthomas/refined#895]
Hi, it looks like the repo has been updated for 3.0.0-M3 but there hasn't been a release yet. Would it be possible to create one? Thanks!

**Comment by fthomas** [comment]
Sure. I've just pushed the `v0.9.20` tag and if we're lucky the machines will publish this soon. :crossed_fingers:

**Comment by fthomas** [comment]
0.9.20 is now published.

**Comment by tpolecat** [comment]
And it works! Thanks!
