### ISSUE TITLE
Generate utility method to construct refined-aware case classes automatically

### ISSUE THREAD

**Issue by ngthanhtrung** [fthomas/refined#98]
Hi,

It's convenience to have a utility method to construct case classes automatically. Those case classes will have some field types are refined- ones. Returning value will be an `Option` which resolves if validation passes.

In detail, it would be something like:

``` scala
case class Foo(a: String @@ NonEmpty, b: Int, c: Int @@ Greater[_0] = 1)

object Foo {
  // It would be great to have the following method generated automatically
  def refine(a: String, b: Int, c: Int = 1): Option[Foo] {
    val fooEither = for {
      refinedA <- refineT[NonEmpty](a)
      refinedC <- refineT[Greater[_0]](c)
    } yield Foo(refinedA, b, refinedC)

    fooEither match {
      case Right(r) => Some(r)
      case Left(_) => None
    }
  }
}
```

I wonder if it aligns with this project's roadmap. If yes, I'm happy to submit a pull request because I have a working version using annotation macro right now.

Thanks.

**Comment by fthomas** [comment]
That sounds very interesting! A pull request is definitely welcome. :-)

**Comment by meoguru** [comment]
Which name suits the best for the annotation? What about `Refinable`?

**Comment by fthomas** [comment]
Sorry, I'm too exhausted right now to think about names. (I had a long day.)

**Comment by meoguru** [comment]
OK. I'll work on the pull request first and we can sort it out later. Take care.

**Comment by fthomas** [comment]
Since the future of macros in Scala is currently uncertain, I feel uncomfortable adding more to the code base. Closing for now.
