### ISSUE TITLE
Inconsistency between 0.9.25 and 0.9.26 versions - possible regression

### ISSUE THREAD

**Issue by lewapek** [fthomas/refined#990]
Hey,
it seems that there is inconsistency between 0.9.25 and 0.9.26 versions of the library
Below you can find code snippet showing that with versions <= 0.9.25 `Concrete` type could be passed to function which expects `Base`
With 0.9.26 it's not possible (compilation error)
Is that intentional?

```
  type BaseRefinement = And[Size[Equal[10]], Forall[LetterOrDigit]]
  type Base = String Refined BaseRefinement

  type ConcreteRefinement = And[StartsWith[W.`"001"`.T], BaseRefinement]
  type Concrete = String Refined ConcreteRefinement

  def funBase(b: Base): Unit = println(b)
  def funConcrete(c: Concrete): Unit = println(c)

  val b: Base = "1234567890"
  val c: Concrete = "0012345678"

  funBase(b)
  funBase(c) // with 0.9.26 doesn't compile, with 0.9.25 works fine

  //    funConcrete(b) // doesn't compile on both versions - that's fine
  funConcrete(c)
```

Full code snippet ready to compile can be found here (https://gist.github.com/lewapek/3cbf003a000bbe9bf479607e9967d201)

Thanks :)

**Comment by fthomas** [comment]
https://github.com/fthomas/refined/pull/927 by @matwojcik was the only change in 0.9.26 that was not a version bump. Maybe this issue is related to that change.

**Comment by matwojcik** [comment]
Indeed something got broken during implicits resolution, because the Refinement @lewapek created were pretty complex (nested Ands, Ors). I've moved my instances to lower level implicits and it seem to help, see #994.

**Comment by lewapek** [comment]
Thanks @matwojcik

**Comment by thiloplanz** [comment]
We are also suffering from this regression.

Is the patch from #994 working? If so, can we get this released?
